### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by slime3000fly**
I had to remove the print("using library: %s (version %s)" % (osmgpsmap.__file__, osmgpsmap._version)) statement to make it run on my machine.

Additionaly:

- delete GObject.threads_init() and Gdk.threads_init()
- add gi.require_version('OsmGpsMap', '1.0')

### CODE REVIEW

**Comment by programmin1** [comment]
What operating system/version did you have to make changes for?
Thanks for the PR I will check it out later.

**Comment by slime3000fly** [comment]
I was using Kali Linux version 2023.3.

**Comment by programmin1** [comment]
Unit tests would be welcome too. Do you have any other fixes/PRs, I will probably be able to fix some things before long as an update...

**Comment by slime3000fly** [comment]
For now, I just wanted to share these changes and get the program up and running. In the future, I'll see what I can do with testing.

**Comment by programmin1** [comment]
I made these changes on main branch, this is good. I had deprecation warnings on threads_init as well.
I'm not merging this because those *311.pyc files don't need to be in.

*hacktoberfest-approved tag added.

**Comment by programmin1** [comment]
This is all merged in to master branch along with some other fixes and the beta ability to add other sources, not just Hearham repeaters.
You can test it by adding "https://hearham.com/gmrscsv/oregon.csv" in the settings, currently, any similar format should work.
Can you check that this all still runs and works alright on newer Linux please?

**Pull request closed without merging**
